web:
  image: blog.dpritchett.net
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #  command: [nginx-debug, '-g', 'daemon off;']
  command: [nginx-debug, '-g', 'daemon off;']
  #command: [nginx]
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=blog.dpritchett.net
   - NGINX_PORT=80
